#!/usr/bin/env bash
# Install nginx in web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello Holberton" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
