#!/usr/bin/env bash
# Installing Nginx in server
STR="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=O6_P_ZWwJ3Q;\n"
sed -i "0,/location/ {
    /location/i ${STR}
    }" /etc/nginx/sites-enabled/default
nginx -s reload
