#!/usr/bin/env bash
# Configure a load balancer server
apt-get update
apt-get install -y haproxy=1.6.\*
STR1="frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n"
STR2="backend http_back\n\tbalance roundrobin\n\tserver 1806-web-01 35.185.1.77:80 check\n\tserver 1806-web-02 35.190.146.27:80 check\n"
echo -e $STR1>>/etc/haproxy/haproxy.cfg
echo -e $STR2>>/etc/haproxy/haproxy.cfg
service haproxy restart
