#!/usr/bin/env bash
# 5 - Holberton School + elif - if
i=1
while [ $i -le 13 ]
do
    j=1
    echo "Hour: $(( i - 1 ))"
    while [ $j -le 59 ]
    do
        echo "$j"
        j=$(( j + 1))
    done
    i=$(( i + 1 ))
done
